package priv.kit.ui

internal data class PrivilegeUiScreenState(
    val localNetworkPermissionMissing: Boolean = false,
    val localNetworkPermissionSettingsRequired: Boolean = false,
    val wirelessAdbSupported: Boolean = true,
    val adbTcpPolicy: PrivilegeUiAdbTcpPolicy = PrivilegeUiAdbTcpPolicy.PREFER_EXISTING,
    val tcpPort: Int = 5555,
    val batteryOptimizationPromptVisible: Boolean = false,
    val staticTcpSwitchConfirmation: priv.kit.ui.adb.PrivilegeUiStaticTcpSwitchAction? = null,
    val busy: Boolean = false,
    val runtimeStatus: PrivilegeUiRuntimeStatus = PrivilegeUiRuntimeStatus.DISCONNECTED,
    val runtimeStartSource: PrivilegeUiRuntimeStartSource? = null,
    val serverUid: Int? = null,
    val connectionSerial: Long = 0L,
    val deniedServerPermissions: List<String> = emptyList(),
    val selectedStartupMode: PrivilegeUiStartupMode = PrivilegeUiStartupMode.ADB,
    val startupModes: List<PrivilegeUiStartupMode> = listOf(
        PrivilegeUiStartupMode.ROOT,
        PrivilegeUiStartupMode.ADB,
        PrivilegeUiStartupMode.MANUAL_SHELL,
    ),
    val runtimeProgressText: String? = null,
    val manualShellCommandLine: String? = null,
    val pairingCode: String = "",
    val pairingStatus: PrivilegeUiAdbPairingStatus = PrivilegeUiAdbPairingStatus.NOT_PAIRED,
    val pairingText: String? = null,
    val pairingDialogVisible: Boolean = false,
    val pairingNotificationPermissionWarningVisible: Boolean = false,
    val wirelessDebuggingStatus: PrivilegeUiWirelessAdbStatus = PrivilegeUiWirelessAdbStatus.UNKNOWN,
    val wirelessPairingServiceStatus: PrivilegeUiWirelessAdbStatus = PrivilegeUiWirelessAdbStatus.UNKNOWN,
    val wirelessPairingCheckStatus: PrivilegeUiWirelessAdbStatus = PrivilegeUiWirelessAdbStatus.UNKNOWN,
    val wirelessAdbStatusLoaded: Boolean = false,
    val managedWirelessAdbStatus: PrivilegeUiManagedWirelessAdbStatus =
        PrivilegeUiManagedWirelessAdbStatus.UNKNOWN,
    val wifiConnected: Boolean = false,
    val staticTcp: PrivilegeUiStaticTcpState = PrivilegeUiStaticTcpState(),
    val tcpAuthorizationFailureDialogVisible: Boolean = false,
    val adbKeyFingerprint: String? = null,
    val notificationPairingRunning: Boolean = false,
    val externalStartItems: List<PrivilegeUiExternalStartItemState> = emptyList(),
    val startupLogLines: List<String> = emptyList(),
    val runtimeStartPhase: PrivilegeUiRuntimeStartPhase = PrivilegeUiRuntimeStartPhase.IDLE,
    val runtimeStartProviderId: String? = null,
    val permissionRestrictionStatus: PrivilegeUiPermissionRestrictionStatus =
        PrivilegeUiPermissionRestrictionStatus.UNKNOWN,
    val desiredEnabled: Boolean = false,
    val restartConfirmationTarget: PrivilegeUiServerRestartRequest? = null,
)
