package priv.kit.ui

internal class PrivilegeUiActions(
    val authorizeOrStartExternal: (String) -> Unit = {},
    val canInteract: () -> Boolean = { false },
    val cancelPendingPairingStart: () -> Unit = {},
    val cancelServerRestart: () -> Unit = {},
    val cancelStaticTcpSwitch: () -> Unit = {},
    val clearStartupLog: () -> Unit = {},
    val confirmServerRestart: () -> Unit = {},
    val confirmStaticTcpSwitch: () -> Unit = {},
    val continuePairingWithoutNotification: () -> Unit = {},
    val copyManualCommand: () -> Unit = {},
    val copyStartupLog: () -> Unit = {},
    val copyStaticTcpCommand: () -> Unit = {},
    val disableAutoRecovery: () -> Unit = {},
    val disableTcpMode: () -> Unit = {},
    val dismissTcpAuthorizationFailureDialog: () -> Unit = {},
    val enableTcpMode: () -> Unit = {},
    val openNotificationSettings: () -> Unit = {},
    val requestLocalNetworkPermission: () -> Unit = {},
    val requestBatteryOptimization: () -> Boolean = { false },
    val restartTcpMode: () -> Unit = {},
    val selectStartupMode: (PrivilegeUiStartupMode) -> Unit = {},
    val startInteractive: () -> Unit = {},
    val startNotificationPairing: () -> Unit = {},
    val startRoot: () -> Unit = {},
    val startStaticTcpAdb: () -> Unit = {},
    val startWirelessAdb: () -> Unit = {},
    val stopCurrentStart: () -> Unit = {},
    val stopNotificationPairing: () -> Unit = {},
    val stopServer: () -> Unit = {},
    val submitNotificationPairingCode: () -> Unit = {},
    val updatePairingCode: (String) -> Unit = {},
)
