package priv.kit.ui

internal fun PrivilegeUiState.toScreenState(
    resolveText: (PrivilegeUiText) -> String,
): PrivilegeUiScreenState = PrivilegeUiScreenState(
    localNetworkPermissionMissing = localNetworkPermissionMissing,
    localNetworkPermissionSettingsRequired = localNetworkPermissionSettingsRequired,
    busy = busy,
    runtimeStatus = runtimeStatus,
    runtimeStartSource = runtimeStartSource,
    serverUid = serverInfo?.uid,
    selectedStartupMode = selectedStartupMode,
    startupModes = startupModes,
    runtimeProgressText = runtimeProgressText?.let(resolveText),
    manualShellCommandLine = manualShellCommandLine,
    pairingCode = pairingCode,
    pairingStatus = pairingStatus,
    pairingText = pairingText?.let(resolveText),
    pairingDialogVisible = pairingDialogVisible,
    pairingNotificationPermissionWarningVisible = pairingNotificationPermissionWarningVisible,
    wirelessDebuggingStatus = wirelessDebuggingStatus,
    wirelessPairingServiceStatus = wirelessPairingServiceStatus,
    wirelessPairingCheckStatus = wirelessPairingCheckStatus,
    wirelessAdbStatusLoaded = wirelessAdbStatusLoaded,
    managedWirelessAdbStatus = managedWirelessAdbStatus,
    wifiConnected = wifiConnected,
    staticTcp = staticTcp,
    tcpAuthorizationFailureDialogVisible = tcpAuthorizationFailureDialogVisible,
    adbKeyFingerprint = adbKeyFingerprint,
    notificationPairingRunning = notificationPairingRunning,
    externalStartItems = externalStartItems,
    startupLogLines = startupLogLines,
    runtimeStartPhase = runtimeStartPhase,
    runtimeStartProviderId = runtimeStartProviderId,
    permissionRestrictionStatus = permissionRestrictionStatus,
    connectionSerial = connectionSerial,
    deniedServerPermissions = deniedServerPermissions,
    desiredEnabled = desiredEnabled,
    restartConfirmationTarget = restartConfirmationTarget,
)
