package priv.kit.ui

import android.content.Context

internal fun PrivilegeUiViewModel.screenActions(context: Context): PrivilegeUiActions = PrivilegeUiActions(
    authorizeOrStartExternal = this::authorizeOrStartExternal,
    canInteract = { uiInteractionsEnabled },
    cancelPendingPairingStart = this::cancelPendingPairingStart,
    cancelServerRestart = this::cancelServerRestart,
    cancelStaticTcpSwitch = this::cancelStaticTcpSwitch,
    clearStartupLog = this::clearStartupLog,
    confirmServerRestart = this::confirmServerRestart,
    confirmStaticTcpSwitch = this::confirmStaticTcpSwitch,
    continuePairingWithoutNotification = this::continuePairingWithoutNotification,
    copyManualCommand = this::copyManualCommand,
    copyStartupLog = this::copyStartupLog,
    copyStaticTcpCommand = this::copyStaticTcpCommand,
    disableAutoRecovery = this::disableAutoRecovery,
    disableTcpMode = this::disableTcpMode,
    dismissTcpAuthorizationFailureDialog = this::dismissTcpAuthorizationFailureDialog,
    enableTcpMode = this::enableTcpMode,
    openNotificationSettings = { dispatchNotificationPermissionSettingsRequest(context) },
    requestLocalNetworkPermission = { requestAdbLocalNetworkPermission(context) },
    requestBatteryOptimization = { context.requestPrivilegeUiBatteryOptimizationExemption() },
    restartTcpMode = this::restartTcpMode,
    selectStartupMode = this::selectStartupMode,
    startInteractive = this::startInteractive,
    startNotificationPairing = this::startNotificationPairing,
    startRoot = this::startRoot,
    startStaticTcpAdb = this::startStaticTcpAdb,
    startWirelessAdb = this::startWirelessAdb,
    stopCurrentStart = this::stopCurrentStart,
    stopNotificationPairing = this::stopNotificationPairing,
    stopServer = this::stopServer,
    submitNotificationPairingCode = this::submitNotificationPairingCode,
    updatePairingCode = this::updatePairingCode,
)
