name: build

on:
  workflow_dispatch:

  push:
    branches:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '.github/**'
      - 'docs/**'
      - 'priv-website/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - uses: android-actions/setup-android@v4
        with:
          packages: platform-tools

      - run: ./gradlew publishToMavenLocal

      - run: ./gradlew :priv-ui:jvmTest :priv-ui:testAndroidHostTest :priv-playground:desktopTest

      - run: ./gradlew :priv-sample:assembleRelease

      - uses: actions/upload-artifact@v7
        with:
          name: priv-kit-maven-local
          path: ~/.m2/repository/io/github/priv-kit
          include-hidden-files: true

      - uses: actions/upload-artifact@v7
        with:
          name: priv-sample-legacy-apk
          path: priv-sample/build/outputs/apk/legacy/release/priv-sample-legacy-release.apk
          if-no-files-found: error
          archive: false

      - uses: actions/upload-artifact@v7
        with:
          name: priv-sample-api29-apk
          path: priv-sample/build/outputs/apk/api29/release/priv-sample-api29-release.apk
          if-no-files-found: error
          archive: false
